project:
  type: book
  output-dir: docs

book:
  reader-mode: true
  title: "Uso de Python y librerías geoespaciales para el análisis de datos en el contexto de los incendios forestales "
  author:
    - name: John Gajardo
      orcid: 0000-0003-3368-5491
      email: john.gajardo@uach.cl
    - name: Alén Miranda
      email: alen.miranda@alumnos.uach.cl
    - name: Danko Inzunza 
    - name: Robert Padilla
  date: today
  date-format: medium
  search: true
  chapters:
    - index.qmd
    - 01-python-librerias.qmd
    - 02-geomatica.qmd
    - 03-imagenes.qmd
    - 04-analisisTemporal.qmd
    - 05-modelado.qmd

bibliography: references.bib

format:
  html:
    css: style.css
    theme: 
      light: yeti
      dark: cyborg
    code-fold: false
    lang: es
    code-line-numbers: true
    fig-align: center



