on:
  workflow_dispatch:
  push:
    branches: master

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Create Conda environment
        run: conda env create -f tallerpython.yml

      - name: Initialize Conda
        run: |
          eval "$(conda shell.bash hook)"
          conda activate tallerpython
          conda list
          which python
          python -m pip install jupyter nbformat

      - name: Render and Publish
        run: |
          eval "$(conda shell.bash hook)"
          conda activate tallerpython
          quarto publish gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PUB_FORMAT: html
